# Generated by Django 5.2.8 on 2025-11-06 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_userprofile_user_delete_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('shown_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата показа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает показа'), ('shown', 'Показано пользователю'), ('dismissed', 'Проигнорировано')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscriptions.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'subscription', 'created_at')},
            },
        ),
    ]
